name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.github_pages_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: skywarth/vite-github-pages-deployer@v1.5.0
        id: deploy
        with:
          public_base_path: /honeybear-giggles-website/
          build_path: ./dist
          package_manager: npm
